### ISSUE TITLE
chimera button not working

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-pyworkflow#114]
in md viewer it doesnt launch anything, only prints
"Launching chimera with /home/azazello/soft/scipion3/software/em/chimerax-1.0/bin/ChimeraX /home/azazello/ScipionUserData/projects/TestRelionClassify3D/Runs/000186_ProtRelionClassify3D/extra/relion_it004_class003.mrc"

**Comment by azazellochg** [comment]
if i execute the command myself, it works.

**Comment by azazellochg** [comment]
nothing has changed after 2 weeks, still not working

**Comment by pconesa** [comment]
Weird...

You are going to need to update Xmipp (release 20.07 branch) for this if not updated.

You could also activate the debug mode in scipion that now should activate de debut Mode in java.

That might give us some info, hopefully

**Comment by azazellochg** [comment]
I'm using devel xmipp branch, activating debug doesnt print anything extra

**Comment by azazellochg** [comment]
it is normal that /home/azazello/soft/scipion3/software/em/scipionchimera-1.0 is an empty folder? I've no idea what is this

**Comment by azazellochg** [comment]
ok, after changinf to xmipp 20.07 branch I'm getting this:
```
Launching chimera with /home/azazello/soft/scipion3/software/em/chimerax-1.0/bin/ChimeraX /home/azazello/ScipionUserData/projects/TestRelionClassify3D/Runs/000186_ProtRelionClassify3D/extra/relion_it004_class001.mrc
java.io.IOException: Cannot run program "bash": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at java.base/java.lang.Runtime.exec(Runtime.java:592)
        at java.base/java.lang.Runtime.exec(Runtime.java:451)
        at xmipp.utils.XmippWindowUtil.executeCommand(XmippWindowUtil.java:298)
        at xmipp.viewer.windows.GalleryJFrame.openChimera(GalleryJFrame.java:2407)
        at xmipp.viewer.windows.GalleryJFrame.openWithChimera(GalleryJFrame.java:2440)
        at xmipp.viewer.windows.GalleryJFrame$21.actionPerformed(GalleryJFrame.java:1152)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6631)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6396)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5007)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 42 more
```

**Comment by pconesa** [comment]
No bash? Maybe we can remove the bash -c

**Comment by pconesa** [comment]
Actually the command that showj uses is decided by chimera plugin.

https://github.com/scipion-em/scipion-em/blob/devel/pwem/viewers/showj.py#L303

And chimera get program is doing this

https://github.com/scipion-em/scipion-em-chimera/blob/devel/chimera/__init__.py#L66

I fail to see where bash -c is coming from, unless java does it. I'm on the mobile and it's 7:30 am this could be the reason.

**Comment by pconesa** [comment]
I think I've found it, https://github.com/I2PC/xmippViz/blob/release-20.07/java/src/xmipp/utils/XmippWindowUtil.java#L298

Not sure why that "version" of execute command uses bash!

Can you try to remove the bash and the -c , compile Xmipp (should be fast this time) and check if works?

**Comment by pconesa** [comment]
> it is normal that /home/azazello/soft/scipion3/software/em/scipionchimera-1.0 is an empty folder? I've no idea what is this

For chimerax, now we have a scipion plugin to register commands in chimera that will save /feed scipion with stuff from chimera. That folder is the "flag" for the installer.

**Comment by azazellochg** [comment]
Hi @pconesa thanks for your help. I removed bash -c and it didnt help:
```
java.io.IOException: Cannot run program "/home/azazello/soft/scipion3/software/em/chimerax-1.0/bin/ChimeraX /home/azazello/ScipionUserData/projects/TestRelionClassify3D/Runs/000186_ProtRelionClassify3D/extra/relion_it004_class001.mrc": error=2, No such file or directory
```

**Comment by azazellochg** [comment]
putting /bin/bash -c command doesnt work either.

**Comment by pconesa** [comment]
But you have chimerax there? And the MRC is there too, right?

**Comment by pconesa** [comment]
You are using java11?

**Comment by azazellochg** [comment]
Running above command opens chimeraX without any problems. I'm using java11-openjdk. ChimeraX UI 1.2.1

**Comment by pconesa** [comment]
We believe we have it. The LD_LIBRARY_PATH contains a system path that conflicts chimeraX QT loading process. There is a PR in xmippViz addressing this.

Thanks for reporting.

**Comment by azazellochg** [comment]
I ran scipion installp scipion-em-xmipp -j 8, nothing changed

**Comment by pconesa** [comment]
Code is already merged at release-20-07 branch....any "devel installation" should bring the change.

**Comment by pconesa** [comment]
the change is in java code --> https://github.com/I2PC/xmippViz/pull/37, so xmipp binaries.

**Comment by azazellochg** [comment]
It works! Thanks all for your efforts!
