### ISSUE TITLE
error upo0n refresh runs tree

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-pyworkflow#227]
All 3 core repos in devel. From time to time when clicking Refresh button for the project, I'm getting in the console:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/public/EM/Scipion/miniconda3/envs/.scipion3env/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/gui/project/viewprotocols.py", line 965, in <lambda>
    btn.bind(TK.LEFT_CLICK, lambda e: self._runActionClicked(action))
  File "/lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/gui/project/viewprotocols.py", line 2320, in _runActionClicked
    self.updateRunsGraph(True, reorganize=True)
  File "/lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/gui/project/viewprotocols.py", line 1258, in updateRunsGraph
    self.runsGraph = self.project.getRunsGraph(refresh=refresh,
  File "/lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/project/project.py", line 1377, in getRunsGraph
    runs = [r for r in self.getRuns(refresh=refresh, checkPids=checkPids)
  File "/lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/project/project.py", line 1297, in getRuns
    self.runs = self.mapper.selectAllBatch(objectFilter=lambda o: isinstance(o, pwprot.Protocol))
  File "/lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/mapper/sqlite.py", line 366, in selectAllBatch
    objAll = self.db.selectAllObjects()
  File "/lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/mapper/sqlite.py", line 620, in selectAllObjects
    self.executeCommand(self.selectCmd(ID + ">0", ' ORDER BY parent_id'))
sqlite3.ProgrammingError: Recursive use of cursors not allowed.
```
It does not cause scipion to crash though.

**Comment by pconesa** [comment]
Thanks, Grigory. 
This might be related to our changes in the way we are refreshing the graph. Recently it has been moved to a thread and this might be causing the error.

Although we have tested it a lot before sending the code to devel and never saw this... we are planning an update to revert this behaviour.

And allow us to activate it upon a config variable to give us some time to detect errors like this one and try to fix it.

We'll make a PR to revert the thread behavior for now, and ideally keep fixing error when refreshing in a thread is activated.
