### ISSUE TITLE
Pressing on Cite button in protocol form gives an error

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-pyworkflow#24]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/gui/form.py", line 1660, in _showReferences
    self.showInfo('\n'.join(self.protocol.citations()), "References")
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 1991, in citations
    citations.append('*Package References:*')
AttributeError: 'odict_values' object has no attribute 'append'
```

**Comment by azazellochg** [comment]
After the fix for me it looks like this:
![Screenshot_20191228_091712](https://user-images.githubusercontent.com/6952870/71541574-fdc7ac80-2952-11ea-8c41-4d6400dff1d8.png)

**Comment by pconesa** [comment]
It look correct for me...may be it's a bibtext problem?

![image](https://user-images.githubusercontent.com/785633/71723791-3cb3a180-2e2e-11ea-8acb-099ce5059c40.png)
