### ISSUE TITLE
Tolerate an error in the summary

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-pyworkflow#295]
Scipion v3.0.8 - Eugenius
The package scipion-pyworkflow is out of date. Your version is 3.0.16, the latest is 3.0.17.
The package scipion-em is out of date. Your version is 3.0.11, the latest is 3.0.13.
The package scipion-app is out of date. Your version is 3.0.8, the latest is 3.0.9.
Traceback (most recent call last):
  File "/home/tomo/Software/scipion3-conda/scipion-pyworkflow/pyworkflow/apps/pw_project.py", line 95, in <module>
    openProject(sys.argv[1])
  File "/home/tomo/Software/scipion3-conda/scipion-pyworkflow/pyworkflow/apps/pw_project.py", line 87, in openProject
    projWindow = ProjectWindow(projPath)
  File "/home/tomo/Software/scipion3-conda/scipion-pyworkflow/pyworkflow/gui/project/project.py", line 130, in __init__
    self.switchView(VIEW_PROTOCOLS)
  File "/home/tomo/Software/scipion3-conda/scipion-pyworkflow/pyworkflow/gui/project/base.py", line 145, in switchView
    self.viewWidget = self.viewFuncs[newView](self.footer, self)
  File "/home/tomo/Software/scipion3-conda/scipion-pyworkflow/pyworkflow/gui/project/viewprotocols.py", line 669, in __init__
    c = self.createContent()
  File "/home/tomo/Software/scipion3-conda/scipion-pyworkflow/pyworkflow/gui/project/viewprotocols.py", line 821, in createContent
    self._updateSelection()
  File "/home/tomo/Software/scipion3-conda/scipion-pyworkflow/pyworkflow/gui/project/viewprotocols.py", line 1581, in _updateSelection
    self._fillSummary()
  File "/home/tomo/Software/scipion3-conda/scipion-pyworkflow/pyworkflow/gui/project/viewprotocols.py", line 1858, in _fillSummary
    for line in prot.summary():
  File "/home/tomo/Software/scipion3-conda/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 1950, in summary
    baseSummary += ['', '*ERROR:*', self.getError().get()]
TypeError: can only concatenate str (not "list") to str

This is preventing Scipion to be opened.

**Comment by fonsecareyna82** [comment]
This is already solved
