### ISSUE TITLE
error on import micrographs

### ISSUE THREAD

**Issue by bingwang14** [scipion-em/scipion-pyworkflow#331]
Hi there, 

Here is the error when I import micrographs on  scipion3. Does anyone know how to fix that? thanks in advance.

Error during EXECUTE: 
[Errno 11] Resource temporarily unavailable: 'project.sqlite' -> 'Runs/000002_ProtImportMicrographs/logs/run.db'
Traceback (most recent call last):
  File "/gpfs/home/bwang/software/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/gui/form.py", line 2272, in _close
    message = self.callback(self.protocol, onlySave, doSchedule)
  File "/gpfs/home/bwang/software/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/gui/project/viewprotocols.py", line 1953, in _executeSaveProtocol
    self.project.launchProtocol(prot)
  File "/gpfs/home/bwang/software/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/project/project.py", line 586, in launchProtocol
    pwutils.path.copyFile(self.dbPath, protocol.getDbPath())
  File "/gpfs/home/bwang/software/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/path.py", line 249, in copyFile
    shutil.copy(source, dest)
  File "/gpfs/home/bwang/software/anaconda3/envs/scipion3/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/gpfs/home/bwang/software/anaconda3/envs/scipion3/lib/python3.8/shutil.py", line 275, in copyfile
    fastcopysendfile(fsrc, fdst)
  File "/gpfs/home/bwang/software/anaconda3/envs/scipion3/lib/python3.8/shutil.py", line 172, in fastcopysendfile
    raise err
  File "/gpfs/home/bwang/software/anaconda3/envs/scipion3/lib/python3.8/shutil.py", line 152, in fastcopysendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
BlockingIOError: [Errno 11] Resource temporarily unavailable: 'project.sqlite' -> 'Runs/000002_ProtImportMicrographs/logs/run.db'

**Comment by pconesa** [comment]
Hi this is a known bug on GPFS filesystems that is reported to python developers, but for some design reason they will not "fix". Seems the bug is on GPFS court. https://bugs.python.org/issue43743

To fix this you have a  variable: SCIPION_CANCEL_FASTCOPY that should be set to True

Add SCIPION_CANCEL_FASTCOPY = True in scipion.conf.

scipion.conf can be launched with scipion3 config --show

**Comment by bingwang14** [comment]
Thanks. The problem was solved. I do appreciate it.

**Comment by pconesa** [comment]
Great!
