### ISSUE TITLE
inspect does not work

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-pyworkflow#39]
```
>>>>> "python" "/home/azazello/soft/scipion3/scipion-app/scipion/install/inspect-plugins.py" "relion" 
Traceback (most recent call last):
  File "/home/azazello/soft/scipion3/scipion-app/scipion/install/inspect-plugins.py", line 121, in <module>
    plugin = Domain.getPlugin(pluginName)
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/plugin.py", line 112, in getPlugin
    raise Exception("Invalid plugin '%s'. "
Exception: Invalid plugin 'relion'. Class Plugin with __metaclass__=PluginMeta not found
```

**Comment by azazellochg** [comment]
Works.
