### ISSUE TITLE
Installation query

### ISSUE THREAD

**Issue by mgraham5** [scipion-em/scipion-pyworkflow#426]
Hi,

 I'm installing scipion without root privileges. I follow the installation through as per the installation instructions and the installation succeeds.

However when running the scipion config step, the following error appeared: 

```
Traceback (most recent call last):
  File "/XXX/miniconda3/envs/scipion3/lib/python3.8/site-packages/scipion/__main__.py", line 488, in <module>
    main()
  File "/XXX/miniconda3/envs/scipion3/lib/python3.8/site-packages/scipion/__main__.py", line 265, in main
    from pyworkflow.gui.project import ProjectManagerWindow
  File "/XXX/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/gui/__init__.py", line 34, in <module>
    from .dialog import *
  File "/XXX/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/gui/dialog.py", line 33, in <module>
    from tkcolorpicker import askcolor as _askColor
  File "/XXX/miniconda3/envs/scipion3/lib/python3.8/site-packages/tkcolorpicker/__init__.py", line 21, in <module>
    from tkcolorpicker.colorpicker import ColorPicker, askcolor
  File "/XXX/miniconda3/envs/scipion3/lib/python3.8/site-packages/tkcolorpicker/colorpicker.py", line 43, in <module>
    if getdefaultlocale()[0][:2] == 'fr':
TypeError: 'NoneType' object is not subscriptable
Error at main: 'NoneType' object is not subscriptable
```

This error is not limited to the config as if I install and then just execute scipion then this message appears also. 

I've scoured the help pages looking for similar issues, but am drawing blanks as to what this issue might be! 

Many thanks,

M

**Comment by pconesa** [comment]
This usually happens when the is a Locale wrongly configured. Try to fix your locale settings

Maybe this will help? --> https://askubuntu.com/a/162394/953251

**Comment by azazellochg** [comment]
@pconesa are we still not using tkcolorpicker fork?

**Comment by azazellochg** [comment]
then I don't understand why TypeError was not captured... anyway the issue is resolved
