### ISSUE TITLE
wrong hosts.conf file format

### ISSUE THREAD

**Issue by VolkanOzcoban** [scipion-em/scipion-pyworkflow#454]
Hi there, 

I was just having issues running the final test after installing Scipion (using CUDA v11.8, GCC v10.4.0, Open MPI v4.1.2, and Scipion v3.1.0 on Ubuntu 22.04). The first two tests after installation work (Verify Scipion core plugins by running: scipion3 test --grep pyworkflowtests --run **and** Verify Xmipp compilation by running scipion3 tests pwem.tests.protocols.test_protocols_import_volumes), however, when I try the final test to "Check whether CUDA and MPI work properly" using the following command: 

```
scipion3 tests xmipp3.tests.test_protocols_xmipp_3d.TestXmippProjMatching
``` 
I receive the following command line outputs followed by protocol failed at Step 6 (/bin/sh: 1: Syntax error: "(" unexpected **and** Protocol failed: Command ' mpirun -np %(JOB_NODES)d --map-by node %(COMMAND)s' returned non-zero exit status 2.):

STD OUT:

```shell
Scipion v3.1.0 - Eugenius
Running tests....
Creating project at /home/vishnu/ScipionUserData/projects/TestXmippProjMatching/project.sqlite
>>>> python3 /home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_sync_data.py --download relion_tutorial 
Selected datasets: relion_tutorial
Local copy of dataset relion_tutorial detected.
Checking for updates...
Verifying MD5s...
...done. Updated files: 0
Import Particles
** Running command: 'python3 /home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching" "Runs/000002_ProtImportParticles/logs/run.db" 2 "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching/Runs/000002_ProtImportParticles/logs/run.stdout" "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching/Runs/000002_ProtImportParticles/logs/run.stderr"'
Get a Subset of particles
** Running command: 'python3 /home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching" "Runs/000077_ProtSubSet/logs/run.db" 77 "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching/Runs/000077_ProtSubSet/logs/run.stdout" "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching/Runs/000077_ProtSubSet/logs/run.stderr"'
Import Volume
** Running command: 'python3 /home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching" "Runs/000136_ProtImportVolumes/logs/run.db" 136 "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching/Runs/000136_ProtImportVolumes/logs/run.stdout" "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching/Runs/000136_ProtImportVolumes/logs/run.stderr"'
Run Projection Matching
** Running command: 'python3 /home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching" "Runs/000190_XmippProtProjMatch/logs/run.db" 190 "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching/Runs/000190_XmippProtProjMatch/logs/run.stdout" "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching/Runs/000190_XmippProtProjMatch/logs/run.stderr"'

*************** last 50 lines of STD OUT *********************

   0/   0 sec. .................................
   0/   0 sec. ....................................
   0/   0 sec. .......................................
   0/   0 sec. ..........................................
   0/   0 sec. .............................................
   0/   0 sec. ................................................
   0/   0 sec. ...................................................
   0/   0 sec. ......................................................
   0/   0 sec. .........................................................
   0/   0 sec. ............................................................

Precalculate denominator term of the Wiener filter

Compute differences between CTFs
0000/???? sec. ------------------------------------------------------------
   0/   0 sec. ...
   0/   0 sec. .....
   0/   0 sec. .........
   0/   0 sec. ...........
   0/   0 sec. ...............
   0/   0 sec. ..................
   0/   0 sec. .....................
   0/   0 sec. ........................
   0/   0 sec. ..........................
   0/   0 sec. ..............................
   0/   0 sec. .................................
   0/   0 sec. ....................................
   0/   0 sec. .......................................
   0/   0 sec. ..........................................
   0/   0 sec. .............................................
   0/   0 sec. ................................................
   0/   0 sec. ...................................................
   0/   0 sec. ......................................................
   0/   0 sec. .........................................................
   0/   0 sec. ............................................................
Saving CTF Images
FINISHED: executeCtfGroupsStep, step 2, time 2023-07-21 15:00:34.573916
STARTED: initAngularReferenceFileStep, step 3, time 2023-07-21 15:00:34.655031
FINISHED: initAngularReferenceFileStep, step 3, time 2023-07-21 15:00:34.749632
STARTED: createIterDirsStep, step 4, time 2023-07-21 15:00:34.829607
FINISHED: createIterDirsStep, step 4, time 2023-07-21 15:00:34.869680
STARTED: volumeConvertStep, step 5, time 2023-07-21 15:00:34.949664
FINISHED: volumeConvertStep, step 5, time 2023-07-21 15:00:34.990213
STARTED: angularProjectLibraryStep, step 6, time 2023-07-21 15:00:35.066411
* Create projection library
** Running command: **
 mpirun -np %(JOB_NODES)d --map-by node %(COMMAND)s
FAILED: angularProjectLibraryStep, step 6, time 2023-07-21 15:00:35.121746
*** Last status is failed 
------------------- PROTOCOL FAILED (DONE 6/34)

*************** end of STD OUT *********************

``` 

STD ERR:

```shell
*************** last 50 lines of STD ERR *********************

/bin/sh: 1: Syntax error: "(" unexpected
Traceback (most recent call last):
  File "/home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 204, in run
    self._run()
  File "/home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 255, in _run
    resultFiles = self._runFunc()
  File "/home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 251, in _runFunc
    return self._func(*self._args)
  File "/home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_projmatch/protocol_projmatch.py", line 177, in angularProjectLibraryStep
    runAngularProjectLibraryStep(self, iterN, refN, args, stepParams, **kwargs)
  File "/home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_projmatch/projmatch_steps.py", line 274, in runAngularProjectLibraryStep
    self.runJob('xmipp_angular_project_library', args % stepParams, numberOfMpi=processorsToUse, **kwargs)
  File "/home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1507, in runJob
    self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
  File "/home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 65, in runJob
    process.runJob(log, programName, params,
  File "/home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 56, in runJob
    return runCommand(command, env, cwd)
  File "/home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 71, in runCommand
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
  File "/home/vishnu/miniconda3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' mpirun -np %(JOB_NODES)d --map-by node %(COMMAND)s' returned non-zero exit status 2.
Protocol failed: Command ' mpirun -np %(JOB_NODES)d --map-by node %(COMMAND)s' returned non-zero exit status 2.

*************** end of STD ERR *********************

[   FAILED ] TestXmippProjMatching.testXmippProjMatching


Traceback (most recent call last):
  File "/home/vishnu/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/vishnu/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/vishnu/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/tests/test_protocols_xmipp_3d.py", line 1084, in testXmippProjMatching
    self.launchProtocol(protProjMatch)
  File "/home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/tests/tests.py", line 120, in launchProtocol
    raise Exception("Protocol %s execution failed. See last log lines above for more details." % prot.getRunName())
Exception: Protocol xmipp3 - projection matching execution failed. See last log lines above for more details.


[==========] run 1 tests (10.841 secs)

[  FAILED  ] 1 tests

[  PASSED  ] 0 tests
``` 

Additionally, the following is how the Scipion config file is set up: 
```
[PYWORKFLOW]
CONDA_ACTIVATION_CMD = eval "$(/home/vishnu/miniconda3/bin/conda shell.bash hook)"
NO_COLOR = 
SCIPION_DOMAIN = pwem
SCIPION_FONT_NAME = Helvetica
SCIPION_FONT_SIZE = 10
SCIPION_GUI_CANCEL_AUTO_REFRESH = False
SCIPION_GUI_REFRESH_INITIAL_WAIT = 5
SCIPION_GUI_REFRESH_IN_THREAD = False
SCIPION_LOG = ${SCIPION_HOME}UserData/logs/scipion.log
SCIPION_LOGO = scipion_logo.gif
SCIPION_LOGS = ${SCIPION_HOME}UserData/logs
SCIPION_LOG_FORMAT = %%(message)s
SCIPION_LOG_LEVEL = INFO
SCIPION_NOTES_FILE = notes.txt
SCIPION_NOTIFY = True
SCIPION_PLUGIN_REPO_URL = http://scipion.i2pc.es/getplugins/
SCIPION_PRIORITY_PACKAGE_LIST = pwem tomo pwchem
SCIPION_SOFTWARE = ${SCIPION_HOME}/software
SCIPION_STEPS_CHECK_SEC = 5
SCIPION_SUPPORT_EMAIL = scipion@cnb.csic.es
SCIPION_TESTS = ${SCIPION_HOME}/data/tests
SCIPION_TESTS_CMD = scipion3 tests
SCIPION_TESTS_OUTPUT = ${SCIPION_HOME}UserData/Tests
SCIPION_TEST_NOSYNC = False
SCIPION_TMP = ${SCIPION_HOME}UserData/tmp
SCIPION_UPDATE_SET_ATTEMPTS = 3
SCIPION_UPDATE_SET_ATTEMPT_WAIT = 2
SCIPION_URL = http://scipion.cnb.csic.es/downloads/scipion
SCIPION_URL_SOFTWARE = http://scipion.cnb.csic.es/downloads/scipion/software
SCIPION_URL_TESTDATA = http://scipion.cnb.csic.es/downloads/scipion/data/tests
SCIPION_USER_DATA = ${SCIPION_HOME}UserData
WIZARD_MASK_COLOR = [0.125, 0.909, 0.972]

[PLUGINS]
EM_ROOT = software/em
MAXIT_HOME = %(EM_ROOT)s/maxit-10.1

CUDA = True
CUDA_BIN = /usr/local/cuda-11.8/bin
CUDA_LIB = /usr/local/cuda-11.8/lib64
MPI_BINDIR = /usr/bin
MPI_LIBDIR = /usr/lib/x86_64-linux-gnu/openmpi/lib
MPI_INCLUDE = /usr/lib/x86_64-linux-gnu/openmpi/include
OPENCV = False

``` 

Thank you for all your help!

**Comment by azazellochg** [comment]
Hi, this is a bug I've seen before, thank you for confirming this :)
The problem is the default parallel command in the hosts.conf, which is missing underscores:

mpirun -np %(JOB_NODES)d --map-by node %(COMMAND)s

mpirun -np %_(JOB_NODES)d --map-by node %_(COMMAND)s

**Comment by VolkanOzcoban** [comment]
> Hi, this is a bug I've seen before, thank you for confirming this :) The problem is the default parallel command in the hosts.conf, which is missing underscores:
> 
> ```
> mpirun -np %(JOB_NODES)d --map-by node %(COMMAND)s
> 
> mpirun -np %_(JOB_NODES)d --map-by node %_(COMMAND)s
> ```

Ahhh this makes sense! I was going to put in what was present in hosts.conf but didn't think that was the issue XD. The following is my hosts.conf (makes sense now that I see the two %% and no _ where it should be %_):

```
[localhost]
PARALLEL_COMMAND = mpirun -np %%(JOB_NODES)d --map-by node %%(COMMAND)s
``` 
Changed it to yours and has fixed it. Final output is:

```shell
Scipion v3.1.0 - Eugenius
Running tests....
Creating project at /home/vishnu/ScipionUserData/projects/TestXmippProjMatching/project.sqlite
>>>> python3 /home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_sync_data.py --download relion_tutorial 
Selected datasets: relion_tutorial
Local copy of dataset relion_tutorial detected.
Checking for updates...
Verifying MD5s...
...done. Updated files: 0
Import Particles
** Running command: 'python3 /home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching" "Runs/000002_ProtImportParticles/logs/run.db" 2 "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching/Runs/000002_ProtImportParticles/logs/run.stdout" "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching/Runs/000002_ProtImportParticles/logs/run.stderr"'
Get a Subset of particles
** Running command: 'python3 /home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching" "Runs/000077_ProtSubSet/logs/run.db" 77 "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching/Runs/000077_ProtSubSet/logs/run.stdout" "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching/Runs/000077_ProtSubSet/logs/run.stderr"'
Import Volume
** Running command: 'python3 /home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching" "Runs/000136_ProtImportVolumes/logs/run.db" 136 "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching/Runs/000136_ProtImportVolumes/logs/run.stdout" "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching/Runs/000136_ProtImportVolumes/logs/run.stderr"'
Run Projection Matching
** Running command: 'python3 /home/vishnu/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching" "Runs/000190_XmippProtProjMatch/logs/run.db" 190 "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching/Runs/000190_XmippProtProjMatch/logs/run.stdout" "/home/vishnu/ScipionUserData/projects/TestXmippProjMatching/Runs/000190_XmippProtProjMatch/logs/run.stderr"'
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING: MetaData: Error parsing column 'resolutionFRCRandomNoise' value.
WARNING: MetaData: Error parsing column 'resolutionFreqFourier' value.
WARNING: MetaData: Error parsing column 'resolutionFreqReal' value.
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
WARNING!!! valueIn.failed = True, binding NULL
[ RUN   OK ] TestXmippProjMatching.testXmippProjMatching (59.922 secs)


[==========] run 1 tests (62.210 secs)

[  PASSED  ] 1 tests


``` 

Thank you so much for the speedy response and helpful fix @azazellochg :)

**Comment by azazellochg** [comment]
@VolkanOzcoban great! 

I leave to @pconesa team to find why default hosts.conf has wrong syntax :)

The warnings above have been there for years and are harmless.

**Comment by azazellochg** [comment]
Hi @VolkanOzcoban 

I've just did a clean install of scipion with latest scipioninstaller in both user and dev mode. Installer does not create hosts.conf file by default, so you need to run "scipion3 config", which creates a correct file. Could you explain how you generated hosts file? Was it previously existing file?

**Comment by azazellochg** [comment]
Nevermind! I found the source of the bug!

**Comment by VolkanOzcoban** [comment]
> Nevermind! I found the source of the bug!

Hey @azazellochg 

Apologies for the delayed response. Great to hear you found the source! Hopefully it wasn't a pain to find. 

Will definitely report other bugs I find in other scipion-related plugins :bug: Thanks again for the fix :wrench:

**Comment by pconesa** [comment]
Thanks both for reporting and fixing this.
