### ISSUE TITLE
allow delete output SetOfCTFTomoSeries

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-pyworkflow#478]
from CTF protocols.

At the moment this gives an error which I couldn't decipher:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/gui/project/viewprotocols_extra.py", line 112, in _deleteObject
    if self.parent.windows.askYesNo("Delete object",
AttributeError: 'ProtocolsView' object has no attribute 'windows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/gui/project/viewprotocols_extra.py", line 161, in <lambda>
    lambda: self._deleteObject(obj),
  File "/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/gui/project/viewprotocols_extra.py", line 120, in _deleteObject
    self.parent.windows.showError(str(ex))
AttributeError: 'ProtocolsView' object has no attribute 'windows'
```

**Comment by pconesa** [comment]
Closes by https://github.com/scipion-em/scipion-pyworkflow/pull/479
