### ISSUE TITLE
error syncing dataset?

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-pyworkflow#93]
```
gsharov@hal:~/soft/scipion3/scipion-em$ scipion test sphire.tests.test_protocol_cryolo.TestCryolo
Scipion v3.0 () devel

Running tests....
Creating project at:  /cephfs/gsharov/ScipionUserData/projects/TestCryolo/project.sqlite
>>>> python3 /lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/apps/pw_sync_data.py --download relion_tutorial 
Selected datasets: relion_tutorial
Local copy of dataset relion_tutorial detected.
Checking for updates...
Traceback (most recent call last):
  File "/lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/apps/pw_sync_data.py", line 418, in <module>
    main()
  File "/lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/apps/pw_sync_data.py", line 98, in main
    update(dataset, url=args.url, verbose=args.verbose)
  File "/lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/apps/pw_sync_data.py", line 305, in update
    md5sLocal = dict(x.strip().split() for x in open(join(datasetFolder, 'MANIFEST')))
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by azazellochg** [comment]
False alarm, somehow my MANIFEST file got corrupted..
